version: "3.2"
services:
  php:
    build:
      context: "./docker/php/"
      args:
        PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: php

  apache:
    build:
      context: "./docker/apache/"
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_ROOT}/:/var/www/html/
    container_name: apache

  mysql:
    image: mysql/mysql-server:${MYSQL_VERSION:-latest}
    restart: always
    volumes:
      - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql

  # http://localhost:8080/?server=mysql&username=otherUser&db=freeze&database==freeze
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: mysql
      ADMINER_DEFAULT_DB_NAME: "${DB_NAME}"

networks:
  frontend:
  backend:
volumes:
  data:
